repos:
    # --- GLOBAL / GENERIC HOOKS ---
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: end-of-file-fixer
          - id: trailing-whitespace

    # --- PYTHON SUITE (Isolated to the Python subpackage) ---
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.4.4
      hooks:
          - id: ruff
            files: ^packages/graphtransliterator-py/
            args: [--fix]
          - id: ruff-format
            files: ^packages/graphtransliterator-py/

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.10.0
      hooks:
          - id: mypy
            files: ^packages/graphtransliterator-py/src/
            additional_dependencies: [types-PyYAML, marshmallow]
    - repo: local
      hooks:
          - id: sphinx-build
            name: build sphinx documentation
            entry: poetry run --directory packages/graphtransliterator-py sphinx-build -b html -W --keep-going docs docs/_build/html
            language: system
            files: ^packages/graphtransliterator-py/(docs|src)/
            pass_filenames: false
    # # --- TYPESCRIPT / JS SUITE (Isolated to the TS subpackage) ---
    # - repo: https://github.com/pre-commit/mirrors-eslint
    #   rev: v9.3.0
    #   hooks:
    #     - id: eslint
    #       files: ^packages/graphtransliterator-ts/
    #       additional_dependencies: ['eslint', 'typescript', '@typescript-eslint/parser', '@typescript-eslint/eslint-plugin']
