name: "setup-poetry-env"
description: "Composite action to setup the Python and poetry environment."

inputs:
    python-version:
        required: false
        description: "The python version to use"
        default: "3.10"
    # 👇 Add this new input to handle your subpackage path
    working-directory:
        required: false
        description: "The directory where the python package lives"
        default: "packages/graphtransliterator-py"

runs:
    using: "composite"
    steps:
        - name: Set up python
          uses: actions/setup-python@v5
          with:
              python-version: ${{ inputs.python-version }}

        - name: Install Poetry
          run: pipx install poetry
          shell: bash

        - name: Load cached venv
          id: cached-poetry-dependencies
          uses: actions/cache@v4
          with:
              # 👇 Scopes the cache path to the subpackage
              path: ${{ inputs.working-directory }}/.venv
              # 👇 Finds the correct subpackage lockfile
              key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles(format('{0}/poetry.lock', inputs.working-directory)) }}

        - name: Install dependencies
          if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
          # 👇 Forces poetry to run inside the subpackage folder
          working-directory: ${{ inputs.working-directory }}
          run: poetry install --no-interaction
          shell: bash
